name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13, windows-2022]
        config: [debug, release]
        compiler: [clang-16, gcc-13, msvc]
        exclude:
          - os: ubuntu-22.04
            compiler: msvc
          - os: macos-13
            compiler: msvc
          - os: windows-2022
            compiler: clang-16

          # Temporarily exluding due to GCC complaining about unknown warning
          # options (when using GNU gcc/g++, not Apple's clang)
          - os: macos-13
            config: debug
            compiler: gcc-13
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Fix for actions/runner-images/issues/8659
        uses: mjp41/workaround8649@c8550b715ccdc17f89c8d5c28d7a48eeff9c94a8
        with:
          os: ${{ matrix.os }}

      - name: Dependencies
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          ninja: true
          cmake: true
          clangtidy: true
          cppcheck: true
          ccache: true

      - name: Additional Dependencies (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: sudo apt install xorg-dev

      - name: Configure
        shell: bash
        run: cmake --preset $(echo ${{matrix.compiler}} | sed 's/-.*//')-${{matrix.config}} -DSLIM_BUILD_TESTS=OFF

      - name: Build
        run: cmake --build --preset sandbox-${{matrix.config}}
