name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13, windows-2022]
        config: [debug, release]
        compiler: [clang-16, gcc-13, msvc]
        exclude:
          - os: ubuntu-22.04
            compiler: msvc
          - os: macos-13
            compiler: msvc
          - os: windows-2022
            compiler: clang-16

          # Not supporting (proper) GCC on Mac
          - os: macos-13
            compiler: gcc-13
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Fix for actions/runner-images/issues/8659
        uses: mjp41/workaround8649@c8550b715ccdc17f89c8d5c28d7a48eeff9c94a8
        with:
          os: ${{ matrix.os }}

      - name: Dependencies
        if: ${{ matrix.os != 'macos-13' }}
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          ninja: true
          cmake: true
          ccache: true

      - name: Dependencies (MacOS)
        if: ${{ matrix.os == 'macos-13' }}
        uses: aminya/setup-cpp@v1
        with:
          ninja: true
          cmake: true
          ccache: true

      - name: Clang (MacOS)
        if: ${{ matrix.os == 'macos-13' }}
        run: brew install llvm@16

      - name: Additional Dependencies (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: sudo apt install xorg-dev

      - name: Configure
        if: ${{ matrix.os != 'macos-13' }}
        shell: bash
        run: cmake --preset $(echo ${{matrix.compiler}} | sed 's/-.*//')-${{matrix.config}} -DSLIM_BUILD_TESTS=OFF -DSLIM_ENABLE_TOOLS=OFF

      - name: Configure (MacOS)
        if: ${{ matrix.os == 'macos-13' }}
        shell: bash
        run: cmake --preset clang-${{matrix.config}} -DCMAKE_C_COMPILER=/usr/local/opt/llvm@16/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm@16/bin/clang++ -DSLIM_BUILD_TESTS=OFF -DSLIM_ENABLE_TOOLS=OFF

      - name: Build
        run: cmake --build --preset sandbox-${{matrix.config}}
